### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([26, 28, 45, 89, 70, 27, 32, 35, 59, 85, 64, 11, 64, 11, 86])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[86, 50, 12, 65],
       [64, 80, 21, 45],
       [ 4, 42, 61, 66],
       [92, 98, 42, 52],
       [87, 97, 91, 15],
       [27, 25, 76, 17]])

In [3]:
np.sort(a)[::-1]

array([89, 86, 85, 70, 64, 64, 59, 45, 35, 32, 28, 27, 26, 11, 11])

In [4]:
np.sort(b,axis=0)

array([[ 4, 25, 12, 15],
       [27, 42, 21, 17],
       [64, 50, 42, 45],
       [86, 80, 61, 52],
       [87, 97, 76, 65],
       [92, 98, 91, 66]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [5]:
# code
np.append(a,200)

array([ 26,  28,  45,  89,  70,  27,  32,  35,  59,  85,  64,  11,  64,
        11,  86, 200])

In [6]:
b

array([[86, 50, 12, 65],
       [64, 80, 21, 45],
       [ 4, 42, 61, 66],
       [92, 98, 42, 52],
       [87, 97, 91, 15],
       [27, 25, 76, 17]])

In [7]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[86.        , 50.        , 12.        , 65.        ,  0.5071393 ],
       [64.        , 80.        , 21.        , 45.        ,  0.34577967],
       [ 4.        , 42.        , 61.        , 66.        ,  0.76847181],
       [92.        , 98.        , 42.        , 52.        ,  0.9566098 ],
       [87.        , 97.        , 91.        , 15.        ,  0.09931878],
       [27.        , 25.        , 76.        , 17.        ,  0.99839055]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [8]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [11]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [12]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [13]:
# code
a.shape

(15,)

In [14]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [15]:
np.expand_dims(a,axis=1)

array([[26],
       [28],
       [45],
       [89],
       [70],
       [27],
       [32],
       [35],
       [59],
       [85],
       [64],
       [11],
       [64],
       [11],
       [86]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [16]:
a

array([26, 28, 45, 89, 70, 27, 32, 35, 59, 85, 64, 11, 64, 11, 86])

In [17]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 3,  4,  8,  9, 10, 12, 14]),)

In [18]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([26, 28, 45,  0,  0, 27, 32, 35,  0,  0,  0, 11,  0, 11,  0])

In [19]:
np.where(a%2 == 0,0,a)

array([ 0,  0, 45, 89,  0, 27,  0, 35, 59, 85,  0, 11,  0, 11,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [20]:
# code
a

array([26, 28, 45, 89, 70, 27, 32, 35, 59, 85, 64, 11, 64, 11, 86])

In [21]:
np.argmax(a)

3

In [22]:
b

array([[86, 50, 12, 65],
       [64, 80, 21, 45],
       [ 4, 42, 61, 66],
       [92, 98, 42, 52],
       [87, 97, 91, 15],
       [27, 25, 76, 17]])

In [23]:
np.argmax(b,axis=0)

array([3, 3, 4, 2])

In [24]:
np.argmax(b,axis=1)

array([0, 1, 3, 1, 1, 2])

In [25]:
# np.argmin
np.argmin(a)

11

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [26]:
a

array([26, 28, 45, 89, 70, 27, 32, 35, 59, 85, 64, 11, 64, 11, 86])

In [27]:
np.cumsum(a)

array([ 26,  54,  99, 188, 258, 285, 317, 352, 411, 496, 560, 571, 635,
       646, 732])

In [28]:
b

array([[86, 50, 12, 65],
       [64, 80, 21, 45],
       [ 4, 42, 61, 66],
       [92, 98, 42, 52],
       [87, 97, 91, 15],
       [27, 25, 76, 17]])

In [29]:
np.cumsum(b,axis=1)

array([[ 86, 136, 148, 213],
       [ 64, 144, 165, 210],
       [  4,  46, 107, 173],
       [ 92, 190, 232, 284],
       [ 87, 184, 275, 290],
       [ 27,  52, 128, 145]])

In [30]:
np.cumsum(b)

array([  86,  136,  148,  213,  277,  357,  378,  423,  427,  469,  530,
        596,  688,  786,  828,  880,  967, 1064, 1155, 1170, 1197, 1222,
       1298, 1315])

In [31]:
# np.cumprod
np.cumprod(a)

array([                  26,                  728,                32760,
                    2915640,            204094800,           5510559600,
               176337907200,        6171826752000,      364137778368000,
          30951711161280000,  1980909514321920000,  3343260583831568384,
       -7392251519294242816, -7527790417398464512, -1753933316433641472])

In [32]:
a

array([26, 28, 45, 89, 70, 27, 32, 35, 59, 85, 64, 11, 64, 11, 86])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [33]:
a

array([26, 28, 45, 89, 70, 27, 32, 35, 59, 85, 64, 11, 64, 11, 86])

In [34]:
np.percentile(a,50)

45.0

In [35]:
np.median(a)

45.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [36]:
# code
a

array([26, 28, 45, 89, 70, 27, 32, 35, 59, 85, 64, 11, 64, 11, 86])

In [37]:
np.histogram(a,bins=[0,50,100])

(array([8, 7]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [38]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [39]:
# code
a


array([26, 28, 45, 89, 70, 27, 32, 35, 59, 85, 64, 11, 64, 11, 86])

In [40]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([70])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [41]:
# code
a

array([26, 28, 45, 89, 70, 27, 32, 35, 59, 85, 64, 11, 64, 11, 86])

In [42]:
np.flip(a)

array([86, 11, 64, 11, 64, 85, 59, 35, 32, 27, 70, 89, 45, 28, 26])

In [43]:
b

array([[86, 50, 12, 65],
       [64, 80, 21, 45],
       [ 4, 42, 61, 66],
       [92, 98, 42, 52],
       [87, 97, 91, 15],
       [27, 25, 76, 17]])

In [44]:
np.flip(b,axis=1)

array([[65, 12, 50, 86],
       [45, 21, 80, 64],
       [66, 61, 42,  4],
       [52, 42, 98, 92],
       [15, 91, 97, 87],
       [17, 76, 25, 27]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [45]:
# code
a

array([26, 28, 45, 89, 70, 27, 32, 35, 59, 85, 64, 11, 64, 11, 86])

In [46]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [47]:
# code
a

array([110, 530,  45,  89,  70,  27,  32,  35,  59,  85,  64,  11,  64,
        11,  86])

In [48]:
np.delete(a,[0,2,4])

array([530,  89,  27,  32,  35,  59,  85,  64,  11,  64,  11,  86])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [49]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [50]:
np.intersect1d(m,n)

array([3, 4, 5])

In [51]:
np.setdiff1d(n,m)

array([6, 7])

In [52]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [53]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [54]:
# code
a

array([110, 530,  45,  89,  70,  27,  32,  35,  59,  85,  64,  11,  64,
        11,  86])

In [55]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 45, 75, 70, 27, 32, 35, 59, 75, 64, 25, 64, 25, 75])